export default {
    leftArrowWithBG: require('../assets/icons/leftArrowWithBG.png'),
    logo: require('../assets/icons/logo.png'),
    closeEye: require('../assets/icons/closeEye.png'),
    eye: require('../assets/icons/eye.png'),
    key: require('../assets/icons/key.png'),
    mail: require('../assets/icons/mail.png'),
    darkCross: require('../assets/icons/darkCross.png'),
    homeNavigate: require('../assets/icons/homeNavigate.png'),
    homeActiveNavigate: require('../assets/icons/homeActiveNavigate.png'),
    classesTab: require('../assets/icons/classesTab.png'),
    classesActive: require('../assets/icons/classesActive.png'),
    assessmentsActive: require('../assets/icons/assessmentsActive.png'),
    assessmentsTab: require('../assets/icons/assessmentsTab.png'),
    userImage: require('../assets/icons/userImage.png'),
    childImage: require('../assets/icons/childImage.png'),
    childIcon: require('../assets/icons/childIcon.png'),
    homeWorkImage: require('../assets/icons/homeWorkImage.png'),
    completed: require('../assets/icons/completed.png'),
    pending: require('../assets/icons/pending.png'),
   };